# Generated by Django 5.1 on 2024-12-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ventas', models.IntegerField()),
                ('id_empleado', models.IntegerField()),
                ('id_cliente', models.IntegerField()),
                ('id_producto', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('fecha_venta', models.DateTimeField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
