# Generated by Django 5.1 on 2024-12-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id_sucursal', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=40)),
                ('horario', models.CharField(max_length=40)),
                ('correo_electronico', models.CharField(max_length=20)),
                ('codigo_postal', models.CharField(max_length=20)),
            ],
        ),
    ]
