# Generated by Django 5.1.3 on 2024-12-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id_marca', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('sucursal', models.CharField(max_length=20)),
                ('correo_electronico', models.CharField(max_length=40)),
                ('telefono', models.IntegerField()),
                ('distribuidores', models.CharField(max_length=40)),
                ('tipo_producto', models.CharField(max_length=20)),
            ],
        ),
    ]
