# Generated by Django 5.1.3 on 2024-12-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('rfc', models.IntegerField()),
                ('curp', models.CharField(max_length=40)),
                ('correo_electronico', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
