# Generated by Django 5.1 on 2024-12-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='edad',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='rfc',
            field=models.CharField(max_length=40),
        ),
    ]
