# Generated by Django 5.1 on 2024-12-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juguetes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juguetes',
            name='fecha_fabricacion',
            field=models.DateField(),
        ),
    ]
