# Generated by Django 5.1.3 on 2024-12-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_clientes', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('correo_electronico', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=40)),
                ('forma_pago', models.CharField(max_length=40)),
            ],
        ),
    ]
